version: "3"
services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"
  gradio-app:
    image: easy-web-summarizer
    ports:
      - "7860:7860"
